config/routes.rb
ClubBiz::Application.routes.draw do

  root to: 'users#index'

  resources :comments, :only => [:create]

  match '/index_page', to: 'users#index', via: 'get'

  match '/user_login', to: 'users#login', via: 'post'

  match '/user_logout', to: 'users#logout', via: 'get'

  match '/user_events', to: 'users#show_events', via: 'get'

  match '/create_flag', to: 'users#create_flag', via: 'post'

  match '/destroy_flag', to: 'users#destroy_flag', via: 'delete'

  match '/society_index', to: 'societies#index', via: 'get'

  resource :societies, only: [:new, :create, :update]

  match 'society/:id', to: 'societies#show', via: 'get'

  match '/society_events', to: 'societies#show_events', via: 'get'

  resource :events, only: [:new, :create, :update]

  match '/event_image_upload', to: 'events#event_image_upload', via: [:get, :post]

  match '/event_index', to: 'events#show', via: 'get'

  match '/event_edit', to: 'events#edit', via: 'get'

  match '/event_report', to: 'events#report', via: 'get'

  match '/event_create', to: 'events#create', via: 'post'

  match 'event/:id', to: 'events#show', via: 'get'

  match '/event_show_comments', to: 'events#show_comments', via: 'get'

  match '/search', to: 'users#search', via: 'get'

  match '/ticket_request', to: 'tickets#request_tickets', via: 'get'

  match '/ticket_reserve', to: 'tickets#reserve', via: 'post'

  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end

  match '/my_tickets', to: 'users#show_tickets', via: 'get'

end

app/views/flaggables/_flag_button.html.erb
<!--assume: boolean @flag[:state] -->
<!--        string  @flag[:type]  -->
<!--        int     @flag[:id]    -->

<div class="" id="flaggable-button">
  <% if @flag[:state] %>
    <%= form_tag(destroy_flag_path, :method => 'delete', :remote => true) do %>
      <%= hidden_field_tag(:type, @flag[:type]) %>
      <%= hidden_field_tag(:id, @flag[:id]) %>
      <% if @flag[:type] == 'society' %>
        <%= submit_tag("Following", class: 'btn btn-primary flagged active') %>
      <% else %>
        <%= submit_tag("Liking", class: 'btn btn-primary flagged active') %>
      <% end %>
    <% end %>
  <% else %>
    <%= form_tag(create_flag_path, :method => "post", :remote => true) do %>
      <%= hidden_field_tag(:type, @flag[:type]) %>
      <%= hidden_field_tag(:id, @flag[:id]) %>
      <% if @flag[:type] == 'society' %>
        <%= submit_tag("Follow", class: 'btn btn-default unflagged') %>
      <% else %>
        <%= submit_tag("Like", class: 'btn btn-default unflagged') %>
      <% end %>
    <% end %>
  <% end %>

</div>

app/views/flaggables/flag.js.erb
$("#flaggable-wrapper").html("<%= escape_javascript render('flaggables/flag_button') %>");