config/routes.rb
ClubBiz::Application.routes.draw do

  root to: 'users#index'

  resources :comments, :only => [:create]

  match '/index_page', to: 'users#index', via: 'get'

  match '/user_login', to: 'users#login', via: 'post'

  match '/user_logout', to: 'users#logout', via: 'get'

  match '/user_events', to: 'users#show_events', via: 'get'

  match '/create_flag', to: 'users#create_flag', via: 'post'

  match '/destroy_flag', to: 'users#destroy_flag', via: 'delete'

  match '/society_index', to: 'societies#index', via: 'get'

  resource :societies, only: [:new, :create, :update]

  match 'society/:id', to: 'societies#show', via: 'get'

  match '/society_events', to: 'societies#show_events', via: 'get'

  resource :events, only: [:new, :create, :update]

  match '/event_image_upload', to: 'events#event_image_upload', via: [:get, :post]

  match '/event_index', to: 'events#show', via: 'get'

  match '/event_edit', to: 'events#edit', via: 'get'

  match '/event_report', to: 'events#report', via: 'get'

  match '/event_create', to: 'events#create', via: 'post'

  match 'event/:id', to: 'events#show', via: 'get'

  match '/event_show_comments', to: 'events#show_comments', via: 'get'

  match '/search', to: 'users#search', via: 'get'

  match '/ticket_request', to: 'tickets#request_tickets', via: 'get'

  match '/ticket_reserve', to: 'tickets#reserve', via: 'post'

  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end

  match '/my_tickets', to: 'users#show_tickets', via: 'get'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment_hash = comment_params.merge(user_id: current_user.id)
    @obj = @comment_hash[:commentable_type].constantize.find(@comment_hash[:commentable_id])
    # Not implemented: check to see whether the user has permission to create a comment on this object
    @comment = @obj.comments.new(@comment_hash)
    if @comment.save
      render :partial => "comments/comment", :locals => { :comment => @comment }, :layout => false, :status => :created
    else
      flash[:error] = 'save comments fail.'
    end
  end

  def comment_params
    params.permit(:comment, :commentable_id, :commentable_type)
  end

end

app/views/comments/_comment.html.erb
<div class="comment-item" style="text-align: left;padding-top: 20Px;padding-left: 30px" id="comment-<%= comment.id %> }">
<h4>
    <%= comment.user.name %>:
    <%= comment.comment %>
</h4>
</div>

app/views/comments/_form.html.erb
<div id="comment-form row" style="text-align: center;padding-bottom: 30px">

  <%= form_for comment, :url => comments_path, :method => 'post', remote: true do |f| %>
    <div class="input-group">
      <%= text_field_tag :comment, '', placeholder: 'write your comment', class: 'form-control' %>

    <%= hidden_field_tag :commentable_id, comment.commentable_id %>
    <%= hidden_field_tag :commentable_type, comment.commentable_type %>
    <div class="input-group-btn">
    <span>
      <%= button_tag :submit, class: 'btn btn-primary',style: 'right',data: { disable_with: 'Submitting…' } %>
    </span>
    </div>
      </div>
    </div>
  <% end %>
</div>


<%= javascript_include_tag 'comments/comments' %>

app/views/comments/_show.html.erb
<div class="comments-body">
  <%= render :partial => 'comments/form', locals: { comment: @new_comment } %>

  <%= render :partial => 'comments/comment', :collection => @comments, :as => :comment %>

</div>