config/routes.rb
ClubBiz::Application.routes.draw do

  root to: 'users#index'

  resources :comments, :only => [:create]

  match '/index_page', to: 'users#index', via: 'get'

  match '/user_login', to: 'users#login', via: 'post'

  match '/user_logout', to: 'users#logout', via: 'get'

  match '/user_events', to: 'users#show_events', via: 'get'

  match '/create_flag', to: 'users#create_flag', via: 'post'

  match '/destroy_flag', to: 'users#destroy_flag', via: 'delete'

  match '/society_index', to: 'societies#index', via: 'get'

  resource :societies, only: [:new, :create, :update]

  match 'society/:id', to: 'societies#show', via: 'get'

  match '/society_events', to: 'societies#show_events', via: 'get'

  resource :events, only: [:new, :create, :update]

  match '/event_image_upload', to: 'events#event_image_upload', via: [:get, :post]

  match '/event_index', to: 'events#show', via: 'get'

  match '/event_edit', to: 'events#edit', via: 'get'

  match '/event_report', to: 'events#report', via: 'get'

  match '/event_create', to: 'events#create', via: 'post'

  match 'event/:id', to: 'events#show', via: 'get'

  match '/event_show_comments', to: 'events#show_comments', via: 'get'

  match '/search', to: 'users#search', via: 'get'

  match '/ticket_request', to: 'tickets#request_tickets', via: 'get'

  match '/ticket_reserve', to: 'tickets#reserve', via: 'post'

  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end

  match '/my_tickets', to: 'users#show_tickets', via: 'get'

end

app/views/shared/_alert.html.erb
<div class="alert alert-info alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><%= title %></strong> <%= message %>
</div>

app/views/shared/_carousel.html.erb
<!--Assume there is @image_links available-->

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% unless @image_links.blank? %>
      <% @image_links.each_index do |index| %>
        <li data-target="#carousel-example-generic" data-slide-to="<%= index %>" class="<%= "active" if index == 0 %>"></li>
      <% end %>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <% unless @image_links.blank? %>
      <% @image_links.each_index do |index| %>
        <div class="item <%= 'active' if index == 0 %>">
          <%= image_tag @image_links[index], class: 'center-block' %>
          <div class="carousel-caption">
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

app/views/shared/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header col-xs-12">
    <button id="sidebar-toggle-button" type="button" class="btn-default pull-left visible-sm visible-xs navbar-toggle">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>">Club Biz</a>
    <div class="col-xs-6 col-sm-4 pull-right search-form">
      <form class="navbar-form pull-right" role="search" id="search-form">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search" name="keyword" id="keyword">
          <div class="input-group-btn">
            <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
          </div>
          <div class="input-group-btn btn-group" id="search-filter">
            <button type="button" class="dropdown-toggle btn btn-default" data-toggle="dropdown"><span class="hidden-xs">Filter</span><span class="caret"></span></button>
            <ul class="dropdown-menu" role="menu">
              <li>
                <a href="javascript:void(0);">
                  <label>
                    <input type="checkbox" value="society" checked> Society</label>
                </a>
              </li>
              <li>
                <a href="javascript:void(0);">
                  <label>
                  <input type="checkbox" value="event" checked> Event</label>
                </a>
              </li>
              <li>
                <a href="javascript:void(0);">
                  <label>
                  <input type="checkbox" value="venue" checked> Venue</label>
                </a>
              </li>
            </ul>
          </div>
        </div>

      </form>
    </div>

  </div>

</div>

app/views/shared/_list.html.erb
<div class="list-group" xmlns="http://www.w3.org/1999/html">
  <% unless @results[:events].blank? %>
    <% @results[:events].each do |event| %>
      <%= link_to "/event/#{ event.id }", remote: true, class: 'list-group-item' do %>
        <h4 class="list-group-item-heading"><i class="icon-bag"></i> <%= event.name %></h4>
        <p class="list-group-item-text">
          Time: <%= event.time %> <br>
          Venue: <%= event.venue %>
        </p>
      <% end %>
    <% end %>
  <% end %>
  <% unless @results[:societies].blank? %>
    <% @results[:societies].each do |society| %>
      <%= link_to "/society/#{ society.id }", remote: true, class: 'list-group-item', data: {:society_id => society.id} do %>
        <h4 class="list-group-item-heading"><i class="icon-plane"></i> <%= society.name %></h4>
        <p class="list-group-item-text">
          <%= society.description %>
        </p>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/shared/_sidebar.html.erb
<ul class="nav">
  <li>
    <a href="#" data-toggle="offcanvas" class="visible-md text-center">
      <i class="glyphicon glyphicon-chevron-right"></i>
    </a>
  </li>
</ul>

<% user = role[:user] %>
<% societies = role[:societies] %>
<div id="swipable" data-role-num="<%= societies.length + 1 %>">
  <div id="swipable-item0" data-user-id="<%= user[:id] %>" data-role-type="user" class="swipable-item">
    <div class="role-portrait">
      <%= image_tag(user[:portrait_link], class: 'img-circle img-responsive') %>
    </div>
    <nav>
    <ul class=" lg-sidebar sidebar-ul nav nav-pills nav-stacked hidden-md">
      <li>
        <p style="text-align: center; font-size: 12pt;">
          <span class="pull-left icon-arrow-left role-switch-left"></span>
          <span class="text-center"><%= @_current_user.name %></span>
          <span class="pull-right icon-arrow-right role-switch-right"></span>
        </p>
      </li>
      <li>
        <a href="<%= index_page_path %>">
          <i class="glyphicon glyphicon-home"></i>
          <span class="sidebar-item" style="color:  #428bca">My Feeds</span>
        </a>
      </li>
      <li class="nav-divider"></li>
      <li>
        <a style="color:  #8a6d3b" href="<%= new_societies_url %>">
          <i class="glyphicon glyphicon-home"></i>
          <span class="sidebar-item" >New Society</span>
        </a>
      </li>
      <li class="nav-divider"></li>
      <li>
        <a   style="color:  #3c763d" href="<%= user_events_path %>">
          <i class="icon-diamond"></i>
          <span class="sidebar-item">My Events</span>
        </a>
      </li>
      <li class="nav-divider"></li>
      <li>
        <a style="color:  #a94442" href="//?action=download-manifest&url=http://0.0.0.0:3000/bossTimer.plist>
          <i class="icon-heart"></i>
          <span class="sidebar-item" >My Societies</span>
        </a>
      </li>
      <li class="nav-divider"></li>
      <li>
        <a style="color:  #428bca" href="/my_tickets">
          <i class="icon-star"></i>
          <span class="sidebar-item" >My Tickets</span>
        </a>
      </li>
    </ul>

    <ul class="md-sidebar sidebar-ul nav nav-pills nav-stacked visible-md hidden-sm hidden-xs">
      <li>
        <a href="<%= index_page_path %>">
          <i class="glyphicon glyphicon-home"></i>
        </a>

      </li>
      <li class="nav-divider"></li>
      <li>
        <a href="<%= new_societies_url %>">
          <i class="glyphicon glyphicon-home"></i>
        </a>
      </li>
      <li class="nav-divider"></li>
      <li>
        <a href="<%= user_events_path %>">
          <i class="icon-diamond"></i>
        </a>
      </li>
      <li class="nav-divider"></li>
      <li>
        <a href="#">
          <i class="icon-heart"></i>
        </a>
      </li>
      <li class="nav-divider"></li>
      <li>
        <a href="#">
          <i class="icon-star"></i>
        </a>
      </li>
    </ul>
      </nav>
  </div>

  <% societies.each_index do |index| %>
    <div id="swipable-item<%= index + 1 %>" data-society-id="<%= societies[index] %>" data-role-type="society" class="swipable-item hidden">
      <div class="role-portrait">
        <% image = societies[index][:image] %>
        <% if image.blank? %>
          <%# image_tag('default_portrait.jpg', class: 'img-circle img-responsive') %>
        <% else %>
          <%= image_tag(image, class: 'img-circle img-responsive') %>
        <% end %>
      </div>
      <ul class="lg-sidebar sidebar-ul nav nav-pills nav-stacked hidden-md">
        <li>
          <p style="text-align: center; font-size: 12pt;">
            <span class="pull-left icon-arrow-left role-switch-left"></span>
            <span class="text-center"><%= SocietiesService.new.find_society(societies[index][:id]).name %></span>
            <span class="pull-right icon-arrow-right role-switch-right"></span>
          </p>
        </li>
        <li>
          <a href="<%= root_path %>">
            <i class="glyphicon glyphicon-home"></i>
            <span class="sidebar-item">Society Feeds</span>
          </a>
        </li>
        <li class="nav-divider"></li>
        <li>
          <%= link_to new_events_url(society_id: societies[index][:id]),:style=>'color:  #8a6d3b' do %>
            <i class="glyphicon glyphicon-home"></i>
            <span class="sidebar-item">New Event</span>
          <% end %>
        </li>
        <li class="nav-divider"></li>
        <li>
          <a style="color:  #3c763d" href="<%= society_events_path(id: societies[index][:id]) %>">
            <i class="icon-diamond"></i>
            <span class="sidebar-item">Society Events</span>
          </a>
        </li>
        <li class="nav-divider"></li>
        <li>
          <a style="color:  #a94442" href="#">
            <i class="icon-heart"></i>
            <span class="sidebar-item">Members</span>
          </a>
        </li>
        <li class="nav-divider"></li>
        <li>
          <a style="color:  #428bca" href="#">
            <i class="icon-star"></i>
            <span class="sidebar-item">Edit Profile</span>
          </a>
        </li>
      </ul>

      <ul class="md-sidebar sidebar-ul nav nav-pills nav-stacked visible-md hidden-sm hidden-xs">
        <li>
          <a href="<%= root_path %>">
            <i class="glyphicon glyphicon-home"></i>
          </a>
        </li>
        <li class="nav-divider"></li>
        <li>
          <%= link_to new_events_url(society_id: societies[index][:id]),:style=>'color:  #8a6d3b' do %>
            <i class="glyphicon glyphicon-home"></i>
          <% end %>
        </li>
        <li class="nav-divider"></li>
        <li>
          <a href="#">
            <i class="icon-diamond"></i>
          </a>
        </li>
        <li class="nav-divider"></li>
        <li>
          <a href="<%= society_events_path(id: societies[index][:id]) %>">
            <i class="icon-heart"></i>
          </a>
        </li>
        <li class="nav-divider"></li>
        <li>
          <a href="#">
            <i class="icon-star"></i>
          </a>
        </li>
      </ul>
    </div>
  <% end %>

  <div class="col-xs-12 " style="margin-top: 30px" >
    <%= link_to user_logout_path, style: 'text-decoration: none;' do %>
      <span class="glyphicon glyphicon-off img-responsive" style="text-align: center; font-size: 30px;"></span>
      <%# image_tag('logout.ico', class: 'img-responsive ' , style: 'max-width: 50px', class: 'center-block pull-left') %>

    <% end %>
  </div>

</div>

app/views/shared/_ticket_page.html.erb
<div class="panel panel-primary" id="ticket-info">
  <div class="panel-heading">Panel heading</div>
  <div class="panel-body">
    <ul>
      <% tickets.each do |ticket| %>
        <li>
          <span class="col-xs-4"><strong>Ticket Type:</strong> <%= ticket.ticket_type %></span>
          <span class="col-xs-4"><strong>Price:</strong> $<%= ticket.price %></span>
          <span class="col-xs-4"><strong>Rest Number:</strong> <%= ticket.rest_num %>/<%= ticket.total_num %>left!</span>

          <div class="col-xs-12">
            <label><strong>Reserve NOW:</strong> </label>
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Number of Tickets" data-ticket-id="<%= ticket.id %>">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">BOOK!</button>
              </span>
            </div><!-- /input-group -->
          </div>
        </li>
        <li class="nav-divider"></li>
      <% end %>
    </ul>
  </div>
</div>

<%= javascript_include_tag 'viewer/ticket' %>

app/views/shared/_timeline.html.erb
<div id="timeline-wrapper" class="panel panel-default">
  <div class="panel-heading">
    <!--optional-->
  </div>
  <div class="panel-body">
    <ul class="timeline">
      <!--assume there will be timeline_items available from controller.-->
      <% index = 0 %>
      <% timeline_items.each do |item| %>
        <% if index.odd? then %>
        <li>
        <% else %>
        <li class="timeline-inverted timeline-right">
        <% end %>
          <div class="timeline-badge">

          </div>
          <div class="timeline-panel">

            <%= link_to "/event/#{ item.id }", remote: true, class: 'item-popup-link' do %>
              <span>
              </span>
            <% end %>

            <div class="timeline-heading">
              <h4 class="timeline-title ">
                <%= item.name %>
              </h4>
              <p>
                <small >
                  <%= item.time %>
                </small>
              </p>
            </div>
            <div class="timeline-body">
              <p>
                <%= item.short_description %>
              </p>
            </div>
          </div>
        </li>
        <% index = index + 1 %>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_viewer.html.erb
<!-- carousel from bootstrap-->
<!--TODO-->
<button type="button" class="btn btn-default btn-lg" id="viewer-close-button">
  <span class="glyphicon glyphicon-remove"></span>
</button>

<div>
<%
  image_links =[]

   @viewer_images.each do |image|
     image_links.append(image.try(:event_image).try(:url, :viewer))

   end
   @image_links = image_links
%>
   <%= render 'shared/carousel'%>
</div>
<!--Try to abstract the carousel from multiple use-->


<ul class="list-group ">

  <li class="list-group-item media">
    <a class="pull-left col-xs-4" href="#">
      <%= image_tag('UniLogo.png', class: 'img-responsive viewer-logo') %>
    </a>
    <div class="media-body col-xs-8">
      <h2 class="media-heading col-xs-12" align="left">
        <%= viewer_item.name %>
      </h2>
      <h4> <%= viewer_item.try(:time) %></h4>
      <h4>  <%= viewer_item.try(:venue) %></h4>
    </div>
  </li>
  <li class="list-group-item">
    <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
      Description
    </a>
    <div id="collapse1" class="panel-collapse collapse">

      <%= viewer_item.try(:long_description) %>
      <%= viewer_item.try(:description) %>
    </div>
  </li>
</ul>

<div class="btn-toolbar" role="toolbar">
  <div id="button-list">
    <%= render 'shared/viewer_button' %>
  </div>
</div>

<div id="ticket-list"></div>

<!--comment board will be loaded dynamically via AJAX request-->

<div id="comment-board"></div>

app/views/shared/_viewer_button.html.erb
<ul class="col-xs-12">
  <!-- event button - Like -->
  <li id="flaggable-wrapper">
    <%= render 'flaggables/flag_button' %>
  </li>

  <!-- event button - reserve tickets -->
  <li>
    <button class="btn btn-default">
      <% if @flag[:type] == 'society' %>
        <%= link_to society_events_path(id: @flag[:id]), id: "society-events-btn" do %>
          <span class="hover"></span>
          <span class="caption hidden-xs">Events</span>
          <span class="glyphicon glyphicon-leaf visible-xs"></span>
        <% end %>
      <% else %>
        <%= link_to ticket_request_path(event_id: @viewer_item.id), remote: true, id: 'ticket-reserve-btn' do %>
          <span class="hover"></span>
          <span class="caption hidden-xs">Tickets</span>
          <span class="glyphicon glyphicon-usd visible-xs"></span>
        <% end %>
      <% end %>
    </button>
  </li>

  <!-- event button - discussion  -->
  <li>
    <button class="btn btn-default">
      <%= link_to event_show_comments_path(:event_id => @viewer_item.id), remote: true, id: 'discussion-btn' do %>
        <span class="hover"></span>
        <span class="caption hidden-xs">Discussion</span>
        <span class="glyphicon glyphicon-comment visible-xs"></span>
      <% end %>
    </button>
  </li>

  <!--admin button only-->
  <li>
    <button class="btn btn-default">
      <%= link_to event_report_path(:event_id => @viewer_item.id, :format => :pdf), :target => '_blank', id: 'report-btn' do %>
        <span class="hover"></span>
        <span class="caption">Report</span>
      <% end %>
    </button>
  </li>
  <!--<li>-->
    <!--<a class="edit-btn" href="http://www.facebook.com/creativedash" target="_blank">-->
      <!--<span class="hover"></span>-->
      <!--<span class="caption">Edit</span>-->
    <!--</a>-->
  <!--</li>-->
</ul>

<%= javascript_include_tag 'viewer/viewer' %>